// apps/nuxt/app/pages/openLibrary.vue
<script lang="ts" setup>
import { unwrapFormData } from '@project/helpers/form'

const route = useRoute('openLibrary')
const { data: results } = await useLazyFetch('/api/openLibrary/search', {
  query: {
    q: computed(() => route.query.q),
    page: computed(() => route.query.page),
  },
})

async function updateQuery(event: Event) {
  await navigateTo({ name: 'openLibrary', query: unwrapFormData(event.target) })
}
</script>

<template>
  <div>
    <!-- TODO: lookup uncontrolled Vue forms, b/c this is pretty bad -->
    <form action="/openLibrary" @submit.stop.prevent="updateQuery">
      <label class="input input-bordered flex items-center gap-2">
        <span role="img" aria-label="Search">🔍</span>
        <input type="search" name="q" :value="$route.query.q" class="grow" />
        <kbd class="kbd kbd-sm">Enter</kbd>
      </label>
      <input type="hidden" name="page" :value="1" />
    </form>
    <nav>
      <ul class="menu menu-horizontal bg-base-300">
        <li v-for="i in 3" :key="i">
          <NuxtLink
            :to="{
              name: 'openLibrary',
              query: {
                ...$route.query,
                page: i > 1 ? i : undefined,
              },
            }"
            :class="{
              'menu-active': route.query.page === i.toString() || (!route.query.page && i === 1),
            }"
          >
            page {{ i }}
          </NuxtLink>
        </li>
      </ul>
    </nav>
    <pre>{{ results }}</pre>
  </div>
</template>

// apps/tanstack-start/src/routes/_shell/openLibrary/index.tsx
import { query } from "@app/integrations/openLibrary/search.querySchema";
import { searchServerFn } from "@app/integrations/openLibrary/search.serverFn";
import { unwrapFormData } from "@project/helpers/form";
import {
  Await,
  createFileRoute,
  Link,
  stripSearchParams,
} from "@tanstack/react-router";
import { zodValidator } from "@tanstack/zod-adapter";
import { Suspense } from "react";

// TODO: improve choppy loading behavior: shows cached (stale?) results, then the spinner and then the (fresh) results
export const Route = createFileRoute("/_shell/openLibrary/")({
  component: RouteComponent,
  validateSearch: zodValidator(query),
  search: {
    middlewares: [stripSearchParams({ page: 1, q: "" })],
  },
  loaderDeps: ({ search: { page, q } }) => ({ page, q }),
  loader: async ({ deps }) => ({
    promisedResults: searchServerFn({ data: { page: deps.page, q: deps.q } }),
  }),
});

function RouteComponent() {
  const navigateTo = Route.useNavigate();
  const search = Route.useLoaderDeps();
  const { promisedResults } = Route.useLoaderData();

  return (
    <div>
      <div role="alert" className="alert alert-warning alert-soft my-5 w-auto">
        <span>
          ⚠️ same page navigation does not work properly right now and will
          trigger a full page load or always does a page transition ⚠️
        </span>
      </div>
      <form
        onSubmit={(event) => {
          event.preventDefault();
          event.stopPropagation();

          void navigateTo({
            search: unwrapFormData(event.target),
          });
        }}
      >
        <label className="input input-bordered flex items-center gap-2">
          <span role="img" aria-label="Search">
            🔍
          </span>
          <input
            type="search"
            name="q"
            defaultValue={search.q}
            className="grow"
          />
          <kbd className="kbd kbd-sm">Enter</kbd>
        </label>
        <input type="hidden" name="page" value={1} />
      </form>
      <nav>
        <ul className="menu menu-horizontal bg-base-300">
          {[1, 2, 3].map((i) => (
            <li key={i}>
              <Link
                from={Route.fullPath}
                to="."
                search={{ q: search.q, page: i }}
                // FIXME: sadly this does not work properly for the first page
                // activeProps={{ className: 'menu-active' }}
                className={search.page === i ? "menu-active" : ""}
              >
                {`page ${i}`}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
      <Suspense>
        <Await promise={promisedResults}>
          {(results) => <pre>{JSON.stringify(results, null, 2)}</pre>}
        </Await>
      </Suspense>
    </div>
  );
}
