// apps/nuxt/app/pages/openLibrary.vue
<script lang="ts" setup>
import { unwrapFormData } from '@project/helpers/form'

const route = useRoute('openLibrary')
const { data: results } = useFetch('/api/openLibrary/search', {
  query: {
    q: computed(() => route.query.q),
    page: computed(() => route.query.page),
  },
})

async function updateQuery(event: Event) {
  await navigateTo({ name: 'openLibrary', query: unwrapFormData(event.target) })
}
</script>

<template>
  <div>
    <!-- TODO: lookup uncontrolled Vue forms, b/c this is pretty bad -->
    <form action="/openLibrary" @submit.stop.prevent="updateQuery">
      <label class="input input-bordered flex items-center gap-2">
        <span class="sr-only">
          Search
        </span>
        <span aria-hidden>🔍</span>
        <input type="search" name="q" :value="$route.query.q" class="grow">
      </label>
      <input type="hidden" name="page" :value="$route.query.page ?? 1">
    </form>
    <nav>
      <ul class="menu menu-horizontal bg-base-300">
        <li v-for="i in 3" :key="i">
          <NuxtLink
            :to="{
              name: 'openLibrary',
              query: {
                ...$route.query,
                page: i > 1 ? i : undefined },
            }"
            :class="{ 'menu-active': route.query.page === i.toString() || (!route.query.page && i === 1) }"
          >
            page {{ i }}
          </NuxtLink>
        </li>
      </ul>
    </nav>
    <pre>{{ results }}</pre>
  </div>
</template>

// apps/tanstack-start/app/routes/_shell/openLibrary/index.tsx
import { query, searchServerFn } from '@app/openLibrary/search.serverFn'
import { unwrapFormData } from '@project/helpers/form'
import { createFileRoute, Link } from '@tanstack/react-router'
import { zodValidator } from '@tanstack/zod-adapter'

export const Route = createFileRoute('/_shell/openLibrary/')({
  component: RouteComponent,
  // FIXME: will lead to an error with the 'resolve' package -> wait for fix or find solution
  // validateSearch: zodValidator(query),
  /**  @ts-expect-error -- needs 'validateSearch' method  */
  loaderDeps: ({ search: { page, q } }) => ({ page, q }),
  loader: async () =>
    await searchServerFn({ data: { page: 1, q: '' } }),
  // loader: async ({ deps }) =>
  // await searchServerFn({ data: { page: deps.page, q: deps.q } }),
})

function RouteComponent() {
  const navigateTo = Route.useNavigate()
  const search = Route.useLoaderDeps()
  const results = Route.useLoaderData()

  return (
    <div>
      <form
        onSubmit={async (event) => {
          event.preventDefault()
          event.stopPropagation()

          await navigateTo({
            search: unwrapFormData(event.target),
          })
        }}
      >
        <label className="input input-bordered flex items-center gap-2">
          <span className="sr-only">Search</span>
          <span aria-hidden>🔍</span>
          <input
            type="search"
            name="q"
            defaultValue={search.q || ''}
            className="grow"
          />
        </label>
        <input type="hidden" name="page" value={search.page || ''} />
      </form>
      <nav>
        <ul className="menu menu-horizontal bg-base-300">
          {[1, 2, 3].map(i => (
            <li key={i}>
              <Link
                to="/openLibrary"
                search={{ ...search, page: i > 1 ? i : undefined }}
                className={
                  search.page === i || (!search.page && i === 1)
                    ? 'menu-active'
                    : ''
                }
              >
                page
                {' '}
                {i}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
      <pre>{JSON.stringify(results, null, 2)}</pre>
    </div>
  )
}
